import os

seed = os.environ['SEED']
aggregator_address = 'XBC9JOMDXVRTS9VRLULWYBHNGK9BMYMQKKZFDNFFHTJCNCT9LQJQQIBF9PEAUZVRPCRDMXFONZLSYBVJA'

provider = 'http://node01.testnet.iotatoken.nl:16265'

ruud =  {"seed" : "9MUBGYDJKKNBESRMZUGLZOWGXLIOBRSDIHKKSLUCQBISU9FP9IYVPEUQQKRDIYYBXOPSWVSJMLTYNWUUV",
         "address" : 'IWDLSZGXIJGGRIJZQAZWFEMODVB9SETPJQWCVHNOLITEWHQAFX9DVLPFHDXHA9COZUOMRNACKURH9SXEW',
         "public_key" : "public key ruud"
        }

erwin = {"seed" : "9HVUBRGXMBYKHAZSDNNXODDJAFAGY9ERJRSHXYJQIESILM9V9KUFTVGODGNNETGGJQIKTRYGR9QDYXBRN",
        "address" : 'EZSHEAPSJHPHRTELZOSEVKHZL9GEIJIXHT9KZWBO9SXEYLEOIDJRAGGKRPKUEYEHXGAHPLYUY9FOWEGPY',
         "public_key" : "public key erwin"
        }

timen = {"seed" : "ASBYXEJZTONTYNBSAFQRTHDUSCNBWZCYBSAEWJNMR9IVAULQYVVYG9IULBURYWYWPTEZOTI9VYOCGJTTT",
        "address" : 'KIKDCECULCMJUUJXRUVSAJOLWYBJOGKQMAPQUDKVBOOLDATGSUZVDMTWBDHWAHWMCGJMCTUPPTHMZZETD',
         "public_key" : "public key timen"
        }

# hard coded participants, group members can later be retrieved on public
participants = [ruud, erwin, timen]